name: CI de Mi API

# Cuándo se ejecuta: cada vez que hagas "git push" a la rama main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  pruebas:
    runs-on: ubuntu-latest  # GitHub nos presta una compu con Linux

    steps:
    - name: Descargar el código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar librerías
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx  # Necesario para que el test hable con la API

    - name: Correr los Tests
      run: |
        pytest

    - name: Autenticar en GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/1025423900548/locations/global/workloadIdentityPools/github-pool-v2/providers/github-provider'
        service_account: 'github-deployer@project-acf12a19-9bf8-4ac9-8f8.iam.gserviceaccount.com'
